site_name: Tunarr
repo_name: chrisbenincasa/tunarr
repo_url: https://github.com/chrisbenincasa/tunarr
edit_uri: edit/dev/docs/
site_url: https://tunarr.com/
theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  logo: assets/tunarr.png
  features:
    - navigation.tracking
    - navigation.path
    - navigation.sections
    - navigation.indexes
    - content.code.copy
    - content.code.select
    - content.tooltips
    - content.action.edit
    - content.action.view

nav:
  - Home: index.md
  - API Docs: api-docs.html
  - Getting Started:
      - Install: getting-started/installation.md
      - Run: getting-started/run.md
      - Setup: getting-started/setup.md
      - Migration:
          - Migrate to 1.0: getting-started/migration/migrate-to-1.md
  - Configure:
      - Media Sources:
          - configure/media_sources/index.md
          - Plex: configure/media_sources/plex.md
          - Jellyfin: configure/media_sources/jellyfin.md
          - Emby: configure/media_sources/emby.md
          - Local:
              - configure/media_sources/local/index.md
              - Movies: configure/media_sources/local/movies.md
              - Shows: configure/media_sources/local/shows.md
              - Other Video: configure/media_sources/local/other_videos.md
      - FFmpeg:
          - configure/ffmpeg/index.md
          - Transcode Configs: configure/ffmpeg/transcode_config.md
      - Channels:
          - configure/channels/index.md
          - Properties: configure/channels/properties.md
          - Flex: configure/channels/flex.md
          - EPG: configure/channels/epg.md
          - Transcoding: configure/channels/transcoding.md
          - Watermarks: configure/channels/watermarks.md
      - Programming: configure/programming.md
      - Scheduling:
          - configure/scheduling/index.md
          - Concepts: configure/scheduling/concepts.md
          - Slot Editor: configure/scheduling/random-slots.md
          - Time Slots: configure/scheduling/time-slots.md
          - Cyclic Shuffle: configure/scheduling/cyclic-shuffle.md
          - Block Shuffle: configure/scheduling/block-shuffle.md
          #- Balance: configure/scheduling/balance.md
          - Replicate: configure/scheduling/replicate.md
          - Consolidate: configure/scheduling/consolidate.md
      - Library:
          - configure/library/index.md
          - Filler: configure/library/filler.md
          - Custom Shows: configure/library/custom-shows.md
          - Smart Collections: configure/library/smart-collections.md
      - Clients:
          - configure/clients/index.md
          - Plex: configure/clients/plex.md
          - Jellyfin: configure/clients/jellyfin.md
  - Misc.:
      - Search: misc/search.md
      - Common Issues: misc/common-issues.md
      #- Troubleshooting: misc/troubleshooting.md
  - Development:
      - Contributing: dev/contributing.md

markdown_extensions:
  - admonition
  - abbr
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - docs-extras/includes/definitions.md
  - tables

extra_css:
  - stylesheets/extra.css

extra:
  status:
    new: Alpha only!

plugins:
  - glightbox
  - search

watch:
  - docs-extras/includes
