version: '3.8'
services:
  tunarr:
    # image: chrisbenincasa/tunarr:edge
    # Uncomment along with runtime below to enable HW accel
    image: chrisbenincasa/tunarr:edge
    container_name: tunarr
    ports:
      - 8088:8000
    # Uncomment if using the Nvidia container
    runtime: nvidia
    environment:
      - LOG_LEVEL=${TUNARR_LOG_LEVEL:-INFO}
    # volumes:
      # The host path is relative to the location of the compose file
      # This can also use an absolute path. 
      # 
      # Uncomment if migrating from dizquetv. Chnage the host path
      # to the location of your dizquetv "database"
      # - ./.dizquetv:/.dizquetv